:imagesdir: ../assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript

= Defining the Editor

To define the editor the main parts are defining the projection

== Defining Projections

The layout for everything in ProjectIt is defined using boxes.
A box is a rectangular area in the editor.
The are many different types of boxes in ProjectIt, e.g. a LabelBox for static text, a TextBox for editable text,
and SVG box for SVG graphics, etc. etc.
The first step in creating a projectional editor is to define the projection for language.
To do this, you need to define a mapping from the constructs in your language to _boxes_.

A small example to start with:

image::mapping-example-stringliteral.svg[]

In the language we are using we have the concept of a _StringLiteral_.
The projection maps this to a horizontal list of a quote `"`,
an editable text with the `value` of the `StringLiteral` and then another quote `"`.

In TypeScript this projection might look something like:
[source]
----
new HorizontalListBox( [
        new LabelBox("\""),
        new TextBox(stringLiteral.value),
        new LabelBox("\"")
    ]);
----

The user needs to be able to interacts with the projection.
To be able to define such user interaction, we need to be able to know
which part of the projection the user is working with.

Therefore we need to know of which element in the model/AST a box is a projection
and also be able to distinguish the different boxes for one element.
For this purpose we give each `Box` in the projection a _role_.

image::mapping-example-stringliteral-with-roles.svg[]

In this picture the roles are shown above the boxes in green.
We can now show the full typescript code for creating this projection.
Given  that `literal` is the `StringLiteral` object:

[source]
----
include::{src-dir}/demo/src/editor/DemoProjection.ts[tag=StringLiteral]
----
<1> The overall horizontal list box to group everything
<2> The first label box for the start quote
<3> The text box for the value of the string literal
<4> The second label box for the end quote

All box roles within the projection for a specific element should have a unique role.
This way we can identify every box buy its model element + its role.

[[actions,ActionTitle]]
== Actions
User actions in ProjectIt are attached to boxes.
This is done by attaching one or more *box roles* to an action.

Let's take a look at the definition of a behavior:
````
export interface PiBehavior {
    /**
     * The trigger to activate this behavior
     */
    trigger: PiTriggerType;

    /**
     * The box roles in which this trigger is active
     */
    activeInBoxRoles: string[];

    /**
     * Optional callback function that returns whether the trigger is applicable for the specific box.
     */
    isApplicable?: (box: Box) => boolean;
    boxRoleToSelect?: string;
    caretPosition?: PiCaret;
}
````

== Box
A Box is an abstract class describing the features that are common for all boxes.
As explained earlier, each box has a mandatory model element and role.

There is a number of boxes available

|===
|Primitive Boxes|grouping boxes

|LabelBox | HorizontalListBox
|TextBox | VerticalListBox

|TextBox| GridBox

|SpacerBox|VerticalPiElementListBox
|AliasBox|
|===

== LabelBox
A `LabelBox` shows a non-editable text.
The text itself can either be a fixed string (1),or it can be defined as a function (2).
Being a function allows the label text to change dynamically,
depending on the result value of the function.

[source]
....
new LabelBox(element, "role", "fixed text")         <1>
new LabelBox(element, "role", () => element.value)  <2>
....

== TextBox
A `TextBox` shows an editable text.
In addition to the element and the role a text box needs two function parameters.
The first function to get the value of the text,
the second function to set the value of the text.

[source]
----
new TextBox(
    element,
    "role",
    () => element.stringValue,
    (newValue: string) => element.stringValue = newValue
)
----

Theer are two options you can set for a `TextBox`:

----
----

These options control what happens when a textbox becomes empty, i.e. contains no characters.

== SvgBox
An `SvgBox` shows a single SVG image.

== ListBox
A `ListBox` is a list of boxes, either horizontally or vertically.
The ListBox itself is abstract.

=== HorizontalListBox
A `HorizontalListBox` show a list of child boxes next to each other horizontally.

=== VerticalListBox
A `VerticalListBox` show a list of child boxes next to each other vertically.

=== VerticalPiElementListBox
A `VerticalPiElementListBox` show a list of PiElement objects,
where each PiElement will be shown according to the defined projection.

== GridBox
A `GridBox` is used to show boxes in a tabular fashion.

== SelectBox
A `SelectBox` is used to show a selection to the user.

== AliasBox
An `AliasBox` is a box where the user can type text (printable characters),
which is used as an alias for some action.
