:imagesdir: ../assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript
:listing-caption: Code Sample

= Editor Actions
The interaction of the user with the projected AST is done through actions, to enable the user to change the model and add elements to it. (All actions described here can be found in `packages/demo/src/editor/TutorialProjection.ts`.)

First of all take a look at the built-in default behavior of the editor:

- Inside a TextBox the text can be _edited_.
- Using the _arrow keys_ the user can navigate the projection.
- Using _Ctrl-Arrow_ the user can navigate up and down the model/AST.
- When an element is selected, it can be deleted with the _DEL_ key.

=== Actions for Adding an Element to a List
Certainly the user must be able to add a new entity to the model, for instance to add an element to the end of a list. For this we add an `AliasBox` at the end of the vertical list of entities. An `AliasBox` is a predefined box where the user can type text (printable characters), which is used as an alias for some action. Note the role of the box: [green]#end-of-entity-list#

.Add AliasBox
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=ModelBox4]
----

Secondly, we define an action.

.Define the Action
[source]
----
include::{src-dir}/demo/src/editor/CoreTestActions.ts[tag=CreateEntityAction]
----
<1> The action is attached to each box with the role "end-of-entity-list".
This means that the action can be triggered in the `AliasBox` we defined in the projection.

<2> The action will be triggered when the user types `"entity"` inside the.alias box.

<3> We define the executable code for the action. It creates a new `CoreTestEntity` and attaches is to the `CoreTestModel`

<4> We define the focus of the editor. The `Box`  with the role `"entity-name"`
within the entity as returned from the `action` code will get the editor focus.
This ensures that the user can immediately start typing the name of the entity after it has been created.

=== Actions for Creating New Attributes
Building the action to enable the creation of a new `CoreTestAttribute`, a model element with _PrimitiveType_ is done similar to the creation of a new `CoreTestEntity`.

First we add an `AliasBox` to the projection of the attribute list:

.Add AliasBox to Attribute List
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=CreateAttributeAction]
----

Then we create the actual action and attach it to the role of the `AliasBox`.

.Attach Create Attribute Action to AliasBox
[source]
----
include::{src-dir}/demo/src/editor/CoreTestActions.ts[tag=CreateAttributeAction]
----

As you can see, there can be many boxes with the same role in the editor, as long as their model element is different.
This way, the above action is available for each attribute list in each entity.
