:imagesdir: ../assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript

= Developing with ProjectIt

The main prerequisites are: [Node.js](https://nodejs.org/) and [yarn](https://yarnpkg.com/) and lerna.
We are typically using the latest versions of both, although older versions likely work just as well.
You could also try and use NPM instead of yarn.

To install lerna:

    yarn global add lerna

To setup the lerna structure:

    lerna bootstrap

Now you can build projectit with:

    lerna run build

To start the demo projectional editor:

    lerna run start

This will open a browser with the demo app on `http://localhost:3000/`.
The demo app is work in progress.

== Source organisation

* `.idea`: workspace files for the JetBrains' WebStorm that we use.
* `.vscode`: workspace files for the Visual Studio Code IDEs that we use (to be done).
* `dist`: target directory for WebPack.
* `docs`: documentation
* `packages/core`: framework source code.
* `packages/demo`: source code using the framework to implement a projectional editor for the demo language.
    The main entry point is `packages/demo/src/run.ts`.
* `packages/meta`: experimental source code using the framework to implement a projectional editor for a meta language..
* `packages/model`: source code for decorators that can be used to easily implement a language that can be directly used by ProjectIt.
* `packages/server`: source code for a minimalistic model-server used for demo purposes.
* `/*`: the usual suspects.