:imagesdir: ../assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript
:listing-caption: Code Sample

= Installing ProjectIt

The main prerequisites are: https://nodejs.org/[Node.js] and https://yarnpkg.com/[yarn].
We are typically using the latest versions of both, although older versions likely work just as well.
You could also try and use NPM instead of yarn.

To install all dependencies:

    yarn install

To build and run the demo locally:

    yarn start

This will open a browser with the demo app on `http://localhost:3000/`.
The demo app is work in progress.

== Source organisation

* `.idea`: workspace files for the JetBrains' WebStorm that we use.
* `.vscode`: workspace files for the Visual Studio Code IDEs that we use (to be done).
* `dist`: target directory for WebPack.
* `docs`: The documentation, generated by antora from `packages/docs`.
* `packages/core`: framework source code.
* `packages/docs`: documentation
* `packages/demo`: source code using the framework to implement a projectional editor for the demo language.
    The main entry point is `packages/demo/src/run.ts`.
* `packages/meta`: source code using the framework to implement a projectional editor for an experimental meta language..
* `packages/model`: source codefor decorators that can be used to easily implement a language that can be directly used by ProjectIt.
* `/*`: the usual suspects.
