:imagesdir: ../assets/images/
:src-dir: ../../../../../core/src/test
:projectitdir: ../../../../../core
:source-language: javascript

= ProjectIt Sourcecode Documentation

:TO BE DONE

ProjectIt is designed to be an editor only, not a complete language workbench.
Defining the structure of your language is done outside ProjectIt.

This Meta module is a helper module that supports users to specify the language
structure for a TypeScript implementation.

== Source organisation

* (`.idea`: workspace files for the JetBrains' WebStorm that we use.)
* `.vscode`: workspace files for the Visual Studio Code IDEs that we use.
* `dist`: target directory for WebPack.
* `docs`: The documentation, generated by antora from `packages/docs`.
* `packages/core`: framework source code.
* `packages/docs`: documentation
* `packages/meta`: source code using the framework to implement a projectional editor for an experimental meta language. (JOS: Still true???)
* `packages/model`: source codefor decorators that can be used to easily implement a language that can be directly used by ProjectIt.
* `packages/server`: TBD.
* `packages/tools`: TBD.
* In every subfolder of packages: `dist`: target directory for WebPack.
* `/*`: the usual suspects.
