:imagesdir: ../../images
:page-nav_order: 30
:page-parent: Under the Hood
:src-dir: ../../../../core/src
:source-language: javascript
:listing-caption: Code Sample
= Name-Based References

In xref:expressions.adoc[Support for Expressions] we explain that editing expressions is a known challenge
for projectional editors. A second challenge is posed by _references_. Stated in https://www.voelter.de/data/pub/fse2016-projEditing.pdf[Efficiency of Projectional Editing:
A Controlled Experiment] as follows.

[quote, Markus Voelter a.o., Efficiency of Projectional Editing]
____
*References.*
References are based on pointers to the targetnode’s ID. Despite some advantages (e.g., robust
refactorings) of this approach, we observe problems with the tradeoff that the reference target
has to exist at the time the reference is created.  A more robust and intuitive handling of
references is desirable.  While some problems can be solved by language developers (e.g.,
quick fixes to create reference targets), there should be a better way to support references
by the IDE itself.

The approach to references in ProjectIt is to used only name-based references which are resolve
on a need-to basis.
____

== All References are Name-Based
We have chosen to allow only name-based references. Every reference is an instance of `PiElementReference`,
which holds

. the name of the referred element
. the meta-type of the referred element
. a cache of the element itself

This means that the AST is truly a tree, not a graph.

The advantage is that, when in the future multi-file models are allowed, we are not obliged to have the complete
model in memory. Partial models suffice. <TODO add some references to publications>
