:imagesdir: ../images/
:page-nav_order: 90
:page-title: Future Developments
:page-parent: ProjectIt - Introduction
:src-dir: ../../../core/src
:projectitdir: ../../../core
:source-language: javascript
= Wish List for Future Developments

In the future we want to extend ProjectIt with the following features. There is no order
in this list, nor is there any guarantee that the features will be build. We take on a
task at the moment the need for it arises (or, simply when we like doing it).

*	Add the possibility in the validator definition for language engineers to state
their *own error messages* with each rule, instead of using the predefined messages.
*   Allow for *pathname references*, i.e. references that are not a single name but a list of names (pathname).
*	Support *libraries* for language development, like a library with definitions for different
types of expressions.
*   *Third level adaptability* per concept for both the *scoper* and *typer*.
*	Create an *interpreter generator*.
*   Provide a coupling to a *model-to-model generator*.
*   Add an *importer* for link:https://www.jetbrains.com/mps/[Jetbrains MPS, window=_blank] structure models.
*   Create a *diagrammatic view* of the language structure definition.
*   ...

If you are using ProjectIt, and are missing a specific feature, please let us know through info AT projectit.org.
