:imagesdir: ../images/
:page-nav_order: 30
:page-title: Installing and Using ProjectIt
:page-has_children: true
:page-has_toc: false
:src-dir: ../../../core/src
:projectitdir: ../../../core
:source-language: javascript
:listing-caption: Code Sample
= Installing and Using ProjectIt

[#installation]
== Installation

For now (release candidate 0.05), if you want to use ProjectIt, you have to check out the release candidate branch from github.
The main prerequisites are: link:https://nodejs.org/[Node.js, window=_blank], link:https://yarnpkg.com/[yarn, window=_blank],
and link:https://lerna.js.org/[lerna, window=_blank].

We are typically using the latest versions of all, although older versions likely work just as well.
You could also try and use link:https://www.npmjs.com/[NPM, window=_blank] instead of yarn.

*	The code can be found at link:https://github.com/projectit-org/ProjectIt[https://github.com/projectit-org/ProjectIt, window=_blank].
*   Clone branche `development/release-candidate`.
*   If not installed, install lerna:

    yarn global add lerna

*   Setup the lerna structure:

    lerna bootstrap

*   Build ProjectIt:

    lerna run build

*	Run the example Demo language that is included in the build:

    lerna run start

+
(The command opens a browser with an editor for the Demo language on
`link:http://localhost:3000/[http://localhost:3000/, window=_blank]`. If you are
having trouble using the editor, have a look a the key-bindings under the *Help* menu.)

// TODO check the chain of commands

Now you are ready for a closer look at ProjectIt. You can for instance:

* Have a look at how the example language is defined by browsing through the language definition files in
`packages/playground/src/demo/defs`.
* Create your xref:./first-language.adoc[own language].
* Have a look at the xref:./code-organisation.adoc[source code organisation].
* See how you can xref:./commandline.adoc[use ProjectIt from the commandline].
