:imagesdir: ../images/
:page-nav_order: 30
:page-title: Installing and Using ProjectIt
:page-has_children: true
:page-has_toc: false
:src-dir: ../../../core/src
:projectitdir: ../../../core
:source-language: javascript
:listing-caption: Code Sample
= Installing and Using ProjectIt

[#installation]
== Installation

Please, be sure to have link:https://nodejs.org/[node.js, window=_blank], link:https://yarnpkg.com/[yarn, window=_blank],
and link:https://lerna.js.org/[lerna, window=_blank] running. We are typically using the latest versions of all,
although older versions likely work just as well.
You could also try and use link:https://www.npmjs.com/[NPM, window=_blank] instead of yarn.

The simplest manner to start working with ProjectIt is to clone our
link:https://github.com/projectit-org/ProjectIt-example[example project, window=_blank]
from github.

*   Clone branche `master` from https://github.com/projectit-org/ProjectIt-example.
*   First, install all necessary packages:

    yarn install

*   Run the generator and see extra files appearing in the folder /src/picode:

    yarn generate

*   Start the server:

    yarn model-server

*	Open another (bash) terminal, and start the generated editor from it:

    yarn start

+
This command opens your preferred browser with an editor for the Entity language on
`link:http://localhost:3000/[http://localhost:3000/, window=_blank]`. If Chrome is not
your preferred browser, please open the above page using Chrome, because we cannot
ensure that the editor functions completely in other browsers.
+
If you are
having trouble using the editor, have a look at the key-bindings under the *Help* menu.

Now you are ready for a closer look at ProjectIt. You can for instance:

* Have a look at how the example language is defined by browsing through the language definition files in
`/src/defs`,
* Or follow our tutorial to create your xref:./first-language.adoc[own language],
* Have a look at the xref:./code-organisation.adoc[source code organisation],
* See how you can xref:./commandline.adoc[use ProjectIt from the commandline].
