import * as fs from "fs";
import parserTypeScript = require("prettier/parser-typescript");
const prettier = require("prettier/standalone");

export class Helpers {

    public static generateManualFile(path: string, contents: string, message: string) {
        if (!fs.existsSync(path)) {
            fs.writeFileSync(path, contents);
        } else {
            console.log("projectit-generate-editor: user file " + message + " already exists, skipping it.");
        }
    }

    public static pretty(typescriptFile: string, message: string): string {
        try {
            return "// Generated by the ProjectIt Language Generator.\n" +
                prettier.format(typescriptFile, {
                    parser: "typescript",
                    printWidth: 140,
                    tabWidth: 4,
                    plugins: [parserTypeScript]
                });
        } catch (e) {
            console.log("Syntax error in generated code: " + message);
            console.log(e.message);
        }
        return typescriptFile;
    }

    public static createDirIfNotExisting(dir: string) {
        console.log("dir: ["+ dir + "]");
        const parts = dir.split("/");
        let current = ".";
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            current = current + "/" + part;
            if (!fs.existsSync(current)) {
                fs.mkdirSync(current);
            }
        }
    }

}
