:page-title: Customization of the Validator
:page-nav_order: 30
:page-parent: Third Level Customization
:imagesdir: ../images/
:src-dir: ../../../src/tutorial-language/
:source-language: javascript
:listing-caption: Code Sample
= Third Level Customization of the Validator

The validator can be adjusted on level 3 by adding a single Typescript class. This class should implement
the worker part of the visitor pattern, adding checks per node of the AST that is visted.

You can add the Typescript class anywhere, providing you let ProjectIt know where the file can be found through
the ProjectIt configuration.

== The TypeScript Class
* Create a Typescript file somewhere, for instance in `~/picode/validator`. Note, again, to not add it to the `~/picode/validator/gen` folder,
as this will be delete upon regeneration.
* Create a class in this file and let this class implement the generated `<yourLanguageName>CheckerInterface`.
Obviously, `<yourLanguageName>` needs to be replaced by the name of your language.
+
This is the interface to be implemented for the language called `Entity`.
[source]
----
export interface EntityCheckerInterface extends EntityDefaultWorker {
    errorList: PiError[];
}
----
[start=3]
* Let the class extend the generated default AST worker part of the visitor pattern,
which is called `<yourLanguageName>DefaultWorker`.
* Implement one of the operations in the default worker. This operation will override the default implementation. The
error should be pushed onto the `errorList` attribute. Therefore, each error must implement the
xref:../meta-documentation/tools-interfaces/validator-interface.adoc#PiError[PiError] interface.

The result of the above should look something like this:

[source]
----
include::{src-dir}/validator/CustomValidation.ts[tag=custom-validator]
----

In this example only nodes of type `EntityFunction` are checked. If the name of the node equals `determine` than an error is
pushed on the `errorList`.

If you want the walker to stop when an erroneous node is found you
should return `true`, else return `false`.

== The Configuration
You should let ProjectIt know where it can find your Typescript class by adding an instance of your class to the
`customValidations` array in
the file `ProjectitConfiguration`. You will find this file in `~/picode/projectit`.
It is generated once, and wil not be overwritten on regeneration.

Using the above example class, the configuration should look like this:

[source]
----
include::{src-dir}/projectit/ProjectitConfiguration.ts[tag=custom-validator]
----

