// Generated by the Freon Language Generator.
import {
    MobxModelElementImpl,
    observableprim,
    type FreNamedNode,
    type FreParseLocation,
    FreUtils
} from '@freon4dsl/core';

import { runInAction, makeObservable, action } from 'mobx';
/**
 * Class LimitedElement is the implementation of the limited concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to any changes in the state of its properties.
 */
export class LimitedElement extends MobxModelElementImpl implements FreNamedNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<LimitedElement>): LimitedElement {
        const result = new LimitedElement(data.$id);
        if (data.day) {
            result.day = data.day;
        }
        if (data.part) {
            result.part = data.part;
        }
        if (data.name) {
            result.name = data.name;
        }
        if (data.parseLocation) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    static MondayMorning: LimitedElement; // implementation of instance MondayMorning
    static TuesdayMorning: LimitedElement; // implementation of instance TuesdayMorning
    static WednesdayMorning: LimitedElement; // implementation of instance WednesdayMorning
    static ThursdayMorning: LimitedElement; // implementation of instance ThursdayMorning
    static FridayMorning: LimitedElement; // implementation of instance FridayMorning
    static MondayAfternoon: LimitedElement; // implementation of instance MondayAfternoon
    static TuesdayAfternoon: LimitedElement; // implementation of instance TuesdayAfternoon
    static WednesdayAfternoon: LimitedElement; // implementation of instance WednesdayAfternoon
    static ThursdayAfternoon: LimitedElement; // implementation of instance ThursdayAfternoon
    static FridayAfternoon: LimitedElement; // implementation of instance FridayAfternoon
    static $freANY: LimitedElement; // default predefined instance

    readonly $typename: string = 'LimitedElement'; // holds the metatype in the form of a string
    $id: string = ''; // a unique identifier
    // @ts-expect-error something
    parseLocation: FreParseLocation; // if relevant, the location of this element within the source from which it is parsed
    day: number; // implementation of day
    part: number; // implementation of part
    name: string; // implementation of name

    constructor(id?: string) {
        super();
        if (id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, 'day');
        this.day = 0;
        observableprim(this, 'part');
        this.part = 0;
        observableprim(this, 'name');
        this.name = '';

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): LimitedElement {
        const result = new LimitedElement();
        if (this.day) {
            result.day = this.day;
        }
        if (this.part) {
            result.part = this.part;
        }
        if (this.name) {
            result.name = this.name;
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<LimitedElement>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.day !== null && toBeMatched.day !== undefined) {
            result = result && this.day === toBeMatched.day;
        }
        if (result && toBeMatched.part !== null && toBeMatched.part !== undefined) {
            result = result && this.part === toBeMatched.part;
        }
        if (
            result &&
            toBeMatched.name !== null &&
            toBeMatched.name !== undefined &&
            toBeMatched.name.length > 0
        ) {
            result = result && this.name === toBeMatched.name;
        }
        return result;
    }
}

// Because of mobx we need to generate the initialisations outside of the class,
// otherwise the state of properties with primitive type will not be kept correctly.
runInAction(() => {
    LimitedElement.MondayMorning = LimitedElement.create({
        day: 1,
        part: 1,
        name: 'MondayMorning'
    });
    LimitedElement.TuesdayMorning = LimitedElement.create({
        day: 2,
        part: 1,
        name: 'TuesdayMorning'
    });
    LimitedElement.WednesdayMorning = LimitedElement.create({
        day: 3,
        part: 1,
        name: 'WednesdayMorning'
    });
    LimitedElement.ThursdayMorning = LimitedElement.create({
        day: 4,
        part: 1,
        name: 'ThursdayMorning'
    });
    LimitedElement.FridayMorning = LimitedElement.create({
        day: 5,
        part: 1,
        name: 'FridayMorning'
    });
    LimitedElement.MondayAfternoon = LimitedElement.create({
        day: 1,
        part: 2,
        name: 'MondayAfternoon'
    });
    LimitedElement.TuesdayAfternoon = LimitedElement.create({
        day: 2,
        part: 2,
        name: 'TuesdayAfternoon'
    });
    LimitedElement.WednesdayAfternoon = LimitedElement.create({
        day: 3,
        part: 2,
        name: 'WednesdayAfternoon'
    });
    LimitedElement.ThursdayAfternoon = LimitedElement.create({
        day: 4,
        part: 2,
        name: 'ThursdayAfternoon'
    });
    LimitedElement.FridayAfternoon = LimitedElement.create({
        day: 5,
        part: 2,
        name: 'FridayAfternoon'
    });
});
