// Generated by the Freon Language Generator.
// Run this as the main program.
import { RevenueServiceEnvironment } from "../config/gen/RevenueServiceEnvironment";
import { FreonCommandLine } from "./FreonCommandLine";
import { DummyAction } from "./DummyAction";

// ensure language is initialized
const tmp = RevenueServiceEnvironment.getInstance();

// Create the command line object
const cli: FreonCommandLine = new FreonCommandLine();

// Add specific actions to the command line tool
// REPLACE WITH YOUR OWN
cli.addAction(new DummyAction());

// Run it
cli.execute();
