// Generated by the ProjectIt Language Generator.
import { LanguageConceptType } from "./Language";
import { PiElement } from "@projectit/core";

export interface WithType extends PiElement {
    get$Type(): LanguageConceptType;
}
