// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { StarterModelDefaultWorker } from "../utils/gen/index.js";
import { type StarterModelCheckerInterface } from "./gen/StarterModelValidator.js";

export class CustomStarterModelValidator extends StarterModelDefaultWorker implements StarterModelCheckerInterface {
    errorList: FreError[] = [];
}
