// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { FreLanguageXDefaultWorker } from "../utils/gen/index.js";
import { type FreLanguageXCheckerInterface } from "./gen/FreLanguageXValidator.js";

export class CustomFreLanguageXValidator extends FreLanguageXDefaultWorker implements FreLanguageXCheckerInterface {
    errorList: FreError[] = [];
}
