// Generated by the Freon Language Generator.
import {type FreNode, type FreNamedNode, type FreScoper, FreCompositeScoper } from "@freon4dsl/core";

/**
 * Class 'CustomSvelteTestScoper' is meant to be a convenient place to add any
 * custom code for scoping.
 */
export class CustomSvelteTestScoper implements FreScoper {
    mainScoper!: FreCompositeScoper;

    resolvePathName(modelelement: FreNode, doNotSearch: string, pathname: string[], metatype?: string): FreNamedNode {
        // @ts-ignore
        return undefined;
    }

    isInScope(modelElement: FreNode, name: string, metatype?: string, excludeSurrounding?: boolean): boolean {
        // @ts-ignore
        return undefined;
    }

    getVisibleElements(modelelement: FreNode, metatype?: string, excludeSurrounding?: boolean): FreNamedNode[] {
        // @ts-ignore
        return undefined;
    }

    getFromVisibleElements(modelelement: FreNode, name: string, metatype?: string, excludeSurrounding?: boolean): FreNamedNode {
        // @ts-ignore
        return undefined;
    }

    getVisibleNames(modelelement: FreNode, metatype?: string, excludeSurrounding?: boolean): string[] {
        // @ts-ignore
        return undefined;
    }

    additionalNamespaces(element: FreNode): FreNode[] {
        // @ts-ignore
        return undefined;
    }
}
