:imagesdir: ../../images
:page-nav_order: 10
:page-parent: The ProjectIt Interfaces
:page-grand_parent: Under the Hood
:src-dir: ../../../../../core/src
:source-language: javascript
:listing-caption: Code Sample
= PiElement

As ProjectIt uses the AST for projections and behavior, it needs to know about the type of elements in the AST.
To allow ProjectIt to work, each element type that occurrs in the AST needs to implement the `PiElement` interface.
This interface is kept as small as possible, to allow ProjectIt to be used for any AST.

[source]
----
include::{src-dir}/language/PiModel.ts[tag=element-interface]
----

The main two elements in this interface are:

* `piId()`, which should return en unique id for each element in the AST.
* `piContainer()` which should return a descriptor for the container (parent) of an element in the AST.

The two functions `piIsExpression()` and `piIsBinaryExpression()` are only needed when your language
contains expressions, as ProjectIt includes special handling of expressions.
To start with, these functions can be defined to simply return `false`.

Note that ProjectIt does not need to know anything about the structure of your language.
No need to know the availale element type, nor the properties of en element type, nor anything else.
This is by design, as ProjectIt is not meant to be a full Language Workbench,
but instead meant to be used with multiple language workbenches , or none.

