// Generated by the Freon Language Generator.
// TEMPLATE: InterpreterBaseTemplate.interpreterClass(...)
// Generated once, will NEVER be overwritten.

import { InterpreterContext, RtObject, type IMainInterpreter } from "@freon4dsl/core";

import { RevenueServiceInterpreterBase } from "./gen/RevenueServiceInterpreterBase.js";

let main: IMainInterpreter;

/**
 * The class containing all interpreter functions written by the language engineer.
 * This class is initially empty, and will not be overwritten if it already exists.
 */
export class RevenueServiceInterpreter extends RevenueServiceInterpreterBase {
    constructor(m: IMainInterpreter) {
        super();
        main = m;
    }
}
