// Generated by the Freon Language Generator.
import { FreNode, FreNamedNode, FreScoper, FreCompositeScoper, FreNamespace, FreNodeReference } from '@freon4dsl/core';
import { QualifiedName } from '../language/gen/QualifiedName.js'
import { Referable } from '../language/gen/index.js';

/**
 * Class 'CustomScoperTryoutScoper' is meant to be a convenient place to add any
 * custom code for scoping.
 */
export class CustomScoperTryoutScoper implements FreScoper {
    mainScoper: FreCompositeScoper;

    /**
     *   Returns all elements that are visible in the namespace containing '_node'. Note that '_node' can
     *   be any node in the AST, not only namespaces!
     *
     *   When parameter '_metaType' is present, it returns all elements that are an instance of '_metaType'.
     *   There is no default setting for this parameter.
     *
     * @param _node
     * @param _metaType
     */
    getVisibleNodes(_node: FreNode, _metaType?: string): FreNamedNode[] {
        return [];
    }

    /**
     * Returns all nodes and/or node references that represent namespaces which should be added to the namespace
     * represented by '_node'.
     *
     * @param _node
     */
    additionalNamespaces(_node: FreNode): (FreNode | FreNodeReference<FreNamedNode>)[] {
        return [];
    }

    /**
     * Returns all nodes and/or node references that represent namespaces which should be used to replace
     * the parent namespace of the namespace represented by '_node'.
     *
     * @param node
     */
    public replacementNamespaces(node: FreNode): (FreNode | FreNodeReference<FreNamedNode>)[] {
        // console.log('CUSTOM getAlternativeScope for ' + node.freId() + " of type " + node.freLanguageConcept());

        if (!!node && node.freLanguageConcept() == "QualifiedName") {
            let container = node.freOwner();
            if (!!container) {
                if (container.freLanguageConcept() == "QualifiedName") { // note instanceof does not function here!!
                    const myPart:FreNodeReference<Referable> = (container as QualifiedName).part;
                    // console.log('returning PART: ' + myPart.freId() + " of type " + myPart.freLanguageConcept());
                    return [myPart];
                } else {
                    // console.log('returning OWNER: ' + container.freId() + " of type " + container.freLanguageConcept());
                    return [container as FreNamedNode];
                }
            } else {
                console.error("getAlternativeScope: no owner found.");
            }
        }
        return undefined;
    }
}
