// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { MobxModelElementImpl, type FreNode, observablepart } from "../../../ast/index.js";
import { FreUtils } from "../../../util/index.js";
import { FreParseLocation } from '../../../reader/index.js';
import { CalcExpression } from "./internal.js";

import { makeObservable, action } from "mobx";

/**
 * Class OutputField is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class OutputField extends MobxModelElementImpl implements FreNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<OutputField>): OutputField {
        const result = new OutputField(data.$id);
        if (!!data.expression) {
            result.expression = data.expression;
        }
        if (!!data.parseLocation) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "OutputField"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation; // if relevant, the location of this element within the source from which it is parsed

    expression: CalcExpression; // implementation of part 'expression'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "expression");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): OutputField {
        const result = new OutputField();
        if (!!this.expression) {
            result.expression = this.expression.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<OutputField>): boolean {
        let result: boolean = true;
        if (result && !!toBeMatched.expression) {
            result = result && this.expression.match(toBeMatched.expression);
        }
        return result;
    }
}
