:page-title: Editor Definition
:page-nav_order: 20
:page-parent: Tutorials
:imagesdir: ../images/
:src-dir: ../../../src/tutorial-language/defs
:source-language: javascript
:listing-caption: Code Sample
= The Editor Definition

== Three-tier definition
As explained in xref:./first-language.adoc#tiers[Your Own Language - Overview] the generated editor can be defined in three tiers.
For each *concept* in the AST the editor will

. use the _hand-made projection_, when this is present. Otherwise the editor will
. use to the _projection generated from the editor definition_, when this definition is present. Finally, the editor will
. use the _default projection_.

When a *concept* is marked as an *expression concept*, its default projection is usually the one you want to go with,
because of the extra xref:../meta-documentation/expressions.adoc[support for expressions] that is incorporated in it.

The rest of this tutorial explains the second tier: how to write an editor definition (`.edit` file).
For making more adjustments to the projection by adding hand-made projections, see the
tutorial on xref:framework-tutorial.adoc[using the framework].

== The Editor Definition File
In the editor definition file (`.edit` file) you can define a ProjectIt editor by providing extra information
for each *concept* in your language. Currently, you can define the following three items.

*	*Projection*, which is the manner in which the *concept* is shown in the editor.
*	*Trigger*, which is the key or keys your user needs to type to create a new instance of the *concept*.
*	*Symbol*, which is optional and only used for *expressions*. It is the character or character string that is
shown when an *expression* is being added to your user’s model. When the *symbol* is not present, the *trigger* will be used.

=== Projections
In the `.edit` file a *projection* is defined between angular brackets. Everything within the brackets, except
the parts surrounded by *${ }*, is taken literally, including any indentation.
[source]
----
include::{src-dir}/LanguageDefinition.edit[tag=literal]
----

When the indentation of the opening and closing brackets aligns, this indentation is not taken into account. The
above example will show the text "This is" at the beginning of the line footnote:[This is not completely true. There will
be no indentation in the block that is generated by this projection. However, the projection as a whole may be indented
because it is included in another (bigger) projection.], but the text "for every concept of type Text"
will be shown with an indentation of 8 spaces. If the closing bracket would be positioned on the line after the text,
and it would have been indented with 8 spaces, then the text "for every concept of type Text"
would be shown without any indentation.

[source]
----
include::{src-dir}/LanguageDefinition.edit[tag=indentation]
----

Using ‘[+’ you can indicate that a newline should be added.
[source]
----
include::{src-dir}/LanguageDefinition.edit[tag=newlines]
----

=== Including Subprojections

Using *${ }* you tell ProjectIt to include a property. Its projection is defined by the projection for its concept.

In the following example `${self.condition}` is a property of type `BooleanLiteralExpression`.
It will be projected according to the definition for this concept, whereas `${self.whenTrue}` is a
property of type `EntityExpression`, which is abstract. This property
will be projected according to the definition for subtype of `EntityExpression` that is currently found.

[source]
----
include::{src-dir}/LanguageDefinition.edit[tag=subprojection]
----

=== Lists
If a property is a list, you can indicate whether it should be projected horizontally or vertically.
The default is horizontal.

Furthermore, you can add either a _separator_ string in between all elements, or a _terminator_ string after each element. Both are optional.
[source]
----
include::{src-dir}/LanguageDefinition.edit[tag=lists]
----

