:imagesdir: ../images/
:page-nav_order: 06
:page-title: Your Own Language - Overview
:page-parent: Tutorials
:src-dir: ../../../src/tutorial-language/defs
:projectitdir: ../../../core
:source-language: javascript
:listing-caption: Code Sample
:icons: font
= How to Create your Own Language - an Overview

== The Five Parts of a Language Definition
A ProjectIt language definition consists of five parts:

. The language structure, or abstract syntax tree (AST) is defined in files with extension `.ast`.
. The concrete syntax of the language (CST), or editor definition, is defined in files with extension `.edit`.
. The scoping is defined in files with extension `.scope`.
. The typing is defined in files with extension `.type`.
. The validation is defined in files with extension `.valid`.

And yes, you can use multiple files to define one of the parts. For instance, ProjectIt will combine
multiple .ast files into one AST definition.

More on the content of each of these files can be found in the respective tutorials.

[[modelunits]]
== Models and Model Units
Contrary to what is common in the world of
link:https://en.wikipedia.org/wiki/Domain-specific_language[Domain Specific Languages (DSLs)] we believe that a model
is often too large to handle. When dealing with source code, the times have long gone that a complete
application was written in a single file. Since the 1980s every self-respecting programming language has supported modules.
We believe that this approach should also be taken when dealing with models.

Similar to how the source code for a single application is split into modules, every model in ProjectIt is split
into model units. Each model may contain units of multiple types, either an array of units or a single unit.

[source]
----
include::{src-dir}/LanguageDefinition.ast[tag=model]
----

Note that, for now, ProjectIt expects that every unit type is used a single time. In the above example it would
have been wrong when `extraUnit` was of type `EntityModelUnit`.

For more in-depth information about model units (or partial models, as they were called earlier) we refer you to ...
// TODO
<TODO add some references to publications>

[[public]]
== Model Unit Interfaces
Another trick that we owe to ordinary programming is information hiding. In ProjectIt this means that every
Model Unit defines
an interface. The interface determines which elements from the unit are visible to other units in the same model.

In the definition of the language structure, or AST, concepts and properties can be defined to be public.
Only these public parts of a model unit can be referenced in another model unit. The default scoper (the one
from xref:tiers[tier 1]) already takes
the difference between public and private concepts and properties into account.

Note that for your user this amount to a definition at the language level, similar to restrictions in a
programming language that state that only certain types of elements may be exported/imported.

[[tiers]]
== Three-tier Approach
From the five parts of the language definition ProjectIt generates a workbench containing an editor, scoper, typer,
and validator, and some utilities like a parser/deparser.
You, the language engineer, can fine-tune the generated workbench. We call this fine-tuning: working in three tiers.
(Read our xref:../meta-documentation/philosophy.adoc[philosophy] to understand why we have choosen these tiers.)

. In the first tier, based solely on the AST, defaults are generated for every part of the workbench. For instance, the default scoper
simply finds that every name in a model is visible everywhere.
. In the second tier, the other definitions are taken into account. When the definitions for editor,
scoper etc. are present, they are used to generate a more suitable solution. For instance,
the presentation in the editor can be more concise, using certain keywords etc.
. The third tier takes some hand-coding, but produces a result that is extremely adjusted to your needs. More
on how to use the third tier can be found in the tutorial on xref:./framework-tutorial.adoc[Using the Framework].

ProjectIt is able to combine definitions in each tier into one application, where the third tier proceeds the second, and
the second tier proceeds the first. For instance,
the generated editor will per *concept*

. use the _hand-made projection_, when this is present. Otherwise, the editor will
. use the _projection generated from the editor definition_, when this definition is present. Finally, the editor will
. use the _default projection_, the one that is generated when no `.edit` definition file is present.

This three-tier approach makes it possible to create your language step-by-step, in an agile fashion. If you
want to implement custom code, please check the information on the xref:../meta-documentation/philosophy.adoc/interfaces.adoc[interfaces].

For now this approach is implemented for the editor and validator, in future this will also apply to the
scoper and typer.
