:imagesdir: ../../images
:page-nav_order: 20
:page-parent: The ProjectIt Framework
:page-grand_parent: Under the Hood
:src-dir: ../../../../../core/src
:source-language: javascript
:listing-caption: Code Sample
= Writing Actions in TypeScript

In the ProjectIt editor all behavior is defined using actions.
Although ProjectIt is implemented using React, actions abstract away from this implementation.

Each action defines

* The trigger
* The action itself
* The boxes in which the action can be triggered
* An id for internal use

Let's take a look at the definition of a behavior:

[source]
----
include::{src-dir}/editor/PiAction.ts[tag=PiBehavior]
----

User actions are attached to boxes.
This is done by adding these box roles to the `activeInBoxRoles` property of an action.

The `trigger` defines the keys that will trigger execution of the action.

//TODO: describe the optional properties

== Custom Actions
// TODO document custom actions
To Be Done

== Expressions and Binary Expressions
Advanced expression editing is described in xref:../expressions.adoc[Expressions].

== Keyboard Shortcuts
A keyboard shortcut specifies an action that is triggered by special keys, like e.g. Ctrl-A.
