:page-title: Typer Definition
:page-nav_order: 40
:page-parent: Tutorials
:imagesdir: ../images/
:src-dir: ../../../src/tutorial-language/defs
:source-language: javascript
:listing-caption: Code Sample
= The Typer Definition

For now, the typer definition does not support our xref:../intro/three-levels.adoc[three-level approach].
You can manually code your own scoper on the 3rd level, but it is not possible to combine this with the
scopers on the 1st and 2nd levels.

This tutorial
describes the possibilities of defining a typer in the typer definition file (with extension `.type`).

In the typer definition you provide the information necessary to do type checking.

== Types
First, you have to
indicate which concepts are considered to be types in your language.

Note that we assume that either
there is a concept that is the common super type of all types in your language, or all types in your
language implement the same interface. The first concept or interface in
the types list is considered to be this root of your type hierarchy.
[source]
----
include::{src-dir}/LanguageDefinition.type[tag=types]
----

== Inference Rules

Using *inference rules*, you can indicate how to determine the type of certain concepts. Every concept
for which an inference rule is defined has a type and that type is determined according to the given
rule. In the following example the type of an entity function is the value of its attribute
'declaredType'. Note that in the AST `declaredType` has (meta)type `AttributeType`, which has in the above example
been stated to be a type in your user's language.
[source]
----
include::{src-dir}/LanguageDefinition.type[tag=inference]
----

By stating that an inference rule is *abstract*, you define that the concept does have a type, but the
way its type is determined, is given by the inference rules of its subconcepts.
[source]
----
include::{src-dir}/LanguageDefinition.type[tag=abstract]
----

== Type Conformance Rules
Finally, you have to state your *type conformance rules*. In both inference and conformance rules
it is possible to use the predefined instances of a limited concept.
[source]
----
include::{src-dir}/LanguageDefinition.type[tag=conformance]
----

== Rules that Apply to any Concept
Conformance and other rules can also be defined to apply to *any* concept. Obviously, this means that any instance
of any concept conforms to the given value.
[source]
----
include::{src-dir}/LanguageDefinition.type[tag=anytype]
----
