// Generated by the Freon Language Generator.
import { FreNamespaceInfo, FreScoperBase } from '../../../scoper/index.js';
import { FreNamedNode, FreNode, FreNodeReference } from '../../../ast/index.js';
import { UnitA } from './UnitA.js';
import { UnitB } from './UnitB.js';

/**
 * Class ExportedNamespacesScoper implements the scoper generated from, if present, the scoper definition,
 * otherwise this class implements the default scoper.
 */
export class ExportedNamespacesScoper extends FreScoperBase {
    recursiveImportsA: boolean = false;
    recursiveImportsB: boolean = false;

    /**
     * Returns the replacement namespace if it can be found for 'node'.
     * @param _node
     */
    public replacementNamespace(node: FreNode): FreNamedNode | FreNodeReference<FreNamedNode> | undefined {
        return undefined;
    }

    /**
     * Returns all FreNodes that are defined as additional namespaces for 'node'.
     * @param node
     */
    public importedNamespaces(node: FreNode): FreNamespaceInfo[] {
        const result: FreNamespaceInfo[] = [];
        // namespace addition for UnitA
        if (node instanceof UnitA) {
            // generated based on 'imports'
            for (let loopVariable of node.myRef) {
                result.push(new FreNamespaceInfo(loopVariable, this.recursiveImportsB));
            }
        } else if (node instanceof UnitB) {
            // generated based on 'imports'
            for (let loopVariable of node.myRef) {
                result.push(new FreNamespaceInfo(loopVariable, this.recursiveImportsA));
            }
        }
        return result;
    }
}
