// Generated by the Freon Language Generator.
// import {
//     MobxModelElementImpl,
//     observableprim,
//     observablepartlist,
//     type FreModel,
//     FreLanguage,
//     FreParseLocation,
//     type FreModelUnit,
//     AST,
//     FreUtils,
//     matchElementList,
// } from "@freon4dsl/core";
import { UnitA, UnitB } from "./internal.js";
import { FreModel, FreModelUnit, MobxModelElementImpl, observablepartlist } from '../../../ast';
import { FreParseLocation } from '../../../reader';
import { FreUtils } from '../../../util';
import { matchElementList } from '../../../ast-utils';

import { makeObservable, action, runInAction } from "mobx";
import { FreLanguage } from '../../../language';
import { AST } from '../../../change-manager';

/**
 * Class ScoperModel is the implementation of the model with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to any changes in the state of its properties.
 */
export class ScoperModel extends MobxModelElementImpl implements FreModel {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<ScoperModel>): ScoperModel {
        const result = new ScoperModel(data.$id);
        if (!!data.name) {
            result.name = data.name;
        }
        if (!!data.A_units) {
            data.A_units.forEach((x) => result.A_units.push(x));
        }
        if (!!data.B_units) {
            data.B_units.forEach((x) => result.B_units.push(x));
        }
        if (!!data.parseLocation) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "ScoperModel"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation; // if relevant, the location of this element within the source from which it is parsed
    name: string; // implementation of name
    A_units: UnitA[]; // implementation of part 'A_units'
    B_units: UnitB[]; // implementation of part 'B_units'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepartlist(this, "A_units");
        observablepartlist(this, "B_units");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return true;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): ScoperModel {
        const result = new ScoperModel();
        if (!!this.name) {
            result.name = this.name;
        }
        if (!!this.A_units) {
            this.A_units.forEach((x) => result.A_units.push(x.copy()));
        }
        if (!!this.B_units) {
            this.B_units.forEach((x) => result.B_units.push(x.copy()));
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<ScoperModel>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && !!toBeMatched.A_units) {
            result = result && matchElementList(this.A_units, toBeMatched.A_units);
        }
        if (result && !!toBeMatched.B_units) {
            result = result && matchElementList(this.B_units, toBeMatched.B_units);
        }
        return result;
    }

    /**
     * A convenience method that finds a unit of this model based on its name and 'metatype'.
     * @param name
     * @param metatype
     */
    findUnit(name: string, metatype?: string): FreModelUnit {
        let result: FreModelUnit = null;
        const checkType = metatype !== undefined;
        result = this.getUnits().find(
            (mod) => mod.name === name && (checkType ? FreLanguage.getInstance().metaConformsToType(mod, metatype) : true),
        );
        if (!!result) {
            return result;
        }
        return null;
    }

    /**
     * Replaces a model unit by a new one. Used for swapping between complete units and unit public interfaces.
     * Returns false if the replacement could not be done, e.g. because 'oldUnit' is not a child of this object.
     * @param oldUnit
     * @param newUnit
     */
    replaceUnit(oldUnit: FreModelUnit, newUnit: FreModelUnit): boolean {
        if (oldUnit.freLanguageConcept() !== newUnit.freLanguageConcept()) {
            return false;
        }
        if (oldUnit.freOwnerDescriptor().owner !== this) {
            return false;
        }
        // we must store the interface in the same place as the old unit, which info is held in FreContainer()
        if (oldUnit.freLanguageConcept() === "UnitA" && oldUnit.freOwnerDescriptor().propertyName === "A_units") {
            AST.changeNamed("removeUnit", () => {
                const index = this.A_units.indexOf(oldUnit as UnitA);
                this.A_units.splice(index, 1, newUnit as UnitA);
            });
        } else if (oldUnit.freLanguageConcept() === "UnitB" && oldUnit.freOwnerDescriptor().propertyName === "B_units") {
            AST.changeNamed("removeUnit", () => {
                const index = this.B_units.indexOf(oldUnit as UnitB);
                this.B_units.splice(index, 1, newUnit as UnitB);
            });
        } else {
            return false;
        }
        return true;
    }

    /**
     * Adds a model unit. Returns false if anything goes wrong.
     *
     * @param newUnit
     */
    addUnit(newUnit: FreModelUnit): boolean {
        if (!!newUnit) {
            const myMetatype = newUnit.freLanguageConcept();
            switch (myMetatype) {
                case "UnitA": {
                    AST.changeNamed("addUnit", () => {
                        this.A_units.push(newUnit as UnitA);
                    });
                    return true;
                }
                case "UnitB": {
                    AST.changeNamed("addUnit", () => {
                        this.B_units.push(newUnit as UnitB);
                    });
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Removes a model unit. Returns false if anything goes wrong.
     *
     * @param oldUnit
     */
    removeUnit(oldUnit: FreModelUnit): boolean {
        if (!!oldUnit) {
            const myMetatype = oldUnit.freLanguageConcept();
            switch (myMetatype) {
                case "UnitA": {
                    AST.changeNamed("removeUnit", () => {
                        this.A_units.splice(this.A_units.indexOf(oldUnit as UnitA), 1);
                    });
                    return true;
                }
                case "UnitB": {
                    AST.changeNamed("removeUnit", () => {
                        this.B_units.splice(this.B_units.indexOf(oldUnit as UnitB), 1);
                    });
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Returns an empty model unit of type 'typeName' within 'model'.
     *
     * @param typename
     */
    newUnit(typename: string): FreModelUnit {
        switch (typename) {
            case "UnitA": {
                let unit: UnitA;
                runInAction(() => {
                    unit = UnitA.create({});
                });
                AST.changeNamed("newUnit", () => {
                    this.A_units.push(unit as UnitA);
                });
                return unit;
            }
            case "UnitB": {
                let unit: UnitB;
                runInAction(() => {
                    unit = UnitB.create({});
                });
                AST.changeNamed("newUnit", () => {
                    this.B_units.push(unit as UnitB);
                });
                return unit;
            }
        }
        return null;
    }

    /**
     * Returns a list of model units.
     */
    getUnits(): FreModelUnit[] {
        let result: FreModelUnit[] = [];
        result = result.concat(this.A_units);
        result = result.concat(this.B_units);
        return result;
    }

    /**
     * Returns a list of model units of type 'type'.
     */
    getUnitsForType(type: string): FreModelUnit[] {
        switch (type) {
            case "UnitA": {
                return this.A_units;
            }
            case "UnitB": {
                return this.B_units;
            }
        }
        return [];
    }
}
