// Generated by the ProjectIt Language Generator.
import { AstType, PiElement, PiType, PiTyper, PiTyperPart } from "@projectit/core";
import { DocuProjectTyper } from "../typer/gen/DocuProjectTyper";
import { EuroType, MultiplyExpression, NumberType, ParameterRef, PercentageType } from "../language/gen";

/**
 * Class 'CustomDocuProjectTyperPart' is meant to be a convient place to add any
 * custom code for type checking.
 */
export class CustomDocuProjectTyperPart implements PiTyperPart {
    mainTyper: DocuProjectTyper;
    static fromValidator: boolean = false;

    isType(modelelement: PiElement): boolean | null {
        return null;
    }

    inferType(modelelement: PiElement): PiType | null {
        let result: PiType = null;
        if (CustomDocuProjectTyperPart.fromValidator) {
            if (this.mainTyper.metaTypeOk(modelelement, "ParameterRef")) {
                if (!!(modelelement as ParameterRef)?.attribute) {
                    result = this.mainTyper.inferType(
                        (modelelement as ParameterRef).attribute
                    );
                    return result;
                }
            }
        }
        if (this.mainTyper.metaTypeOk(modelelement, "MultiplyExpression")) {
            const leftType = this.mainTyper.inferType((modelelement as MultiplyExpression).left);
            const rightType = this.mainTyper.inferType((modelelement as MultiplyExpression).right);
            // see if we are multiplying a percentage and an EUR
            if ((leftType.toAstElement() === PercentageType.Percentage && rightType.toAstElement() === EuroType.EUR)
            || (rightType.toAstElement() === PercentageType.Percentage && leftType.toAstElement() === EuroType.EUR)) {
                return AstType.create({ astElement: EuroType.EUR });
            }
            // see if we are multiplying a percentage and a number
            if ((leftType.toAstElement() === PercentageType.Percentage && rightType.toAstElement() === NumberType.Number)
                || (rightType.toAstElement() === PercentageType.Percentage && leftType.toAstElement() === NumberType.Number)) {
                return AstType.create({ astElement: PercentageType.Percentage });
            }
        }
        return null;
    }

    equals(type1: PiType, type2: PiType): boolean | null {
        return null;
    }

    conforms(type1: PiType, type2: PiType): boolean | null {
        return null;
    }

    conformsList(typelist1: PiType[], typelist2: PiType[]): boolean | null {
        return null;
    }

    commonSuper(typelist: PiType[]): PiType | null {
        return null;
    }

    public getSuperTypes(type: PiType): PiType[] | null {
        return null;
    }
}
