:page-layout: default
:page-nav_order: 5
:imagesdir: assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript
= ProjectIt
Projectional Editor for the Web.

== What is ProjectIt?
ProjectIt is a tool for creating web-based projectional editors, based on a TypeScript/JavaScript framework. xref:projectit-main:Projectional-Overview.adoc[Projectional editors] are often used when developing a https://en.wikipedia.org/wiki/Domain-specific_language[Domain Specific Language] (DSL) and its working environment. A tool like ProjectIt is therefore usually part of a https://en.wikipedia.org/wiki/Language_workbench[Language Workbench], next to tools for creating e.g. debuggers, transformers, generators, etc. 

If you want to install ProjectIt see xref:projectit-main:Installation-Guide.adoc[Installing ProjectIt].

== Talking About Language Workbenches
With a tool like ProjectIt, we have to talk about the Workbench that provides all the other tooling for a language developer. 

The core of any Language Workbench is the model repository, which stores the metamodels that are the language definitions.  ProjectIt does not provide such a model repository, nor does it link to a specific repository/Language Workbench. The tool is mostly unopinionated with regards to the models that can be projected, as long as you can make it observed using https://mobx.js.org/[MobX]. ProjectIt can therefore be part of any Language Workbench that upholds this requirement. We expect that in the future ProjectIt will be incorporated in an open Language Workbench as currently being discussed in the community of Language Engineers.

The choice not to tie up ProjectIt to any existing Language Workbench, has a downside. Obviosuly, to create a projectional editor the user must first provide a metamodel of the language to be projected and edited. Without a link to an existing model repository, ProjectIt needs to support its own manner of creating a metamodel. For this see xref:projectit-main:tutorials/Metamodels-Tutorial.adoc[Tutorial 1: Creating a Metamodel].

== An Example of the Kind of Editor Can You Make
The projectional editors that can be created using ProjectIt are all based on the xref:projectit-main:Framework-Description.adoc[ProjectIt Framework], written in TypeScript/Javascript. 

Using the ProjectIt Framework you can build your editor by hand. An example of this can be found in https://github.com/projectit-org/ProjectIt-example[DemoLanguage]. In version 0.0.5 we have added a generator that can do this task for you. We simply needed a point to start. Actually, we have used this example to decide what our generator should produce.

== How to Generate an Editor
The typical workflow for creating an editor is:

1.	Create the metamodel (a metamodel import is envisioned, but not available yet).
2.	Generated an editor.
3.	Improve the look and feel of the editor by giving annotations to the metamodel.
4.	Generate an improved editor.
5.	Repeat steps 3 and 4.

When the editor annotations are not enough to create the required look and feel, the generated code can be changed by hand. Any changes to the generated code will remain during regeneration.

*  xref:projectit-main:tutorials/Metamodels-Tutorial.adoc[Tutorial 1: Creating a Metamodel] tells you about the syntax used for defining metamodels/language definitions.
*  xref:projectit-main:tutorials/Generation-Tutorial.adoc[Tutorial 2: Generating an Editor] shows how to generate an editor using the editor annotations in the metamodel file.
*  xref:pages/framework-tutorial.adoc[Tutorial 3: Editor Look and Feel] gives more information on improving the generated editor by hand.

== Strong Point: Support for Expressions
Many DSLs cater for some sort of expressions. Most language engineers known that it is a complex task to provide editor support especially for binary expressions, and especially in a projectional editor. ProjectIt fully support this task by generating code that recognizes expressions and balances the underlying AST based on the priorities of the operators. In  xref:projectit-main:Supporting-Expressions.adoc[Support for Expressions] you can read more about this. 

== A Peek Inside ProjectIt
Language Engineers and Language Workbench engineers will most likely want to know more about the internal workings of the ProjectIt tool. An introduction to and documentation on the source code can be found in our  xref:projectit-meta:Sourcecode-Documentation.adoc[Source Code Documentation].

== Future Work
The current version is a proof-of-concept. We are working towards a more mature version. Development paths that we envision are:

* Investigate whether ProjectIt can be implemented as Visual Studio Code Extension.
* Separate the metamodel and editor definition annotations and extend the annotations into an full editor definition language.
* Use bootstrapping to provide dedicated editors for the metamodel (.lang file) and the editor definition (.ed file).
* Make many more examples, amongst which a generated editor in a Visual Studio Code Extension.
* Make use of Github as model server.
* Create other tools that have their use within a language workbench, like a scope provider generator (ScopeIt) and a type checker generator (TypeIt).

