:imagesdir: ../assets/images/
:src-dir: ../../../../..
:projectitdir: ../../../../../core
:source-language: javascript

= Tutorial: How to Set Up a Metamodel in ProjectIt

A metamodel or language definiton in ProjectIt consists simply of a set of elements and enumerations. Every element can have:  

* Properties, which always have a Primitive type. 
* Parts, each of which have a (two-way) containment relationship with its parent. 
* References, which refer to another element in the metamodel.

Note that each metamodel must have a unique name.

== An example language definition
Below you will find a part of the Language definition for the Demo Project. In this example you see that decorators are used to indicate parts and references. For now, some hints on generating the editor (_@editor_ decorator) are included in this file. In future, these generator hints will be gathered in a separte file. The complete language definition for the Demo project can be found in _{src-dir}/meta/src/language2/LanguageDefinition.lang_.

.Language Definition for the Demo project
[source]
----
include::{src-dir}/meta/src/language2/LanguageDefinition.lang[tag=MetaModel]
----

== Step by Step
<1> Create a file with extension '.lang' in folder XXXX.
<2> Edit this file and add your language concepts.
<3> Execute 'yarn run start'.
<4> Have a look at your browser where the editor is shown (xref:localhost:XXXX[localhost:XXXX]).
