:imagesdir: ../../assets/images/
:src-dir: ../../../../../..
:projectitdir: ../../../../../../core
:source-language: javascript
:listing-caption: Code Sample

= Projection Tutorial

For an overview of ProjectIt see xref:Projectional-Overview.adoc[Overview].

The first step in creating a projectional editor is to define the projection for language.
To do this, you need to define a mapping from the constructs in your language to _boxes_.

As a starting point we will take a simple language where a model has entities, and entities have attributes.
This model is defined in TypeScript in the folder `packages/demo/src/model`.

The projections in this tutorial are all available in `packages/demo/src/editor/TutorialProjection.ts`.

== Step 1: Project the Model Name
We start with projecting the DemoModel:

.Model Element
[source]
----
include::{src-dir}/demo/src/model/DemoModel.ts[tag=DemoModel]
----

Let's project the model object itself:

.Simple Projection
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=ModelBox1]
----
The projection is a `HorizontalListBox` of a label "Model", followed by the name of the model which is stored in the variable model.name. In the tutorial example the name is "DemoModel".
When we start the editor based on this projection, we see the following:


The first _Model_ is the label,  when it is selected, you cannot edit it.
The text _DemoModel_ can be edited, changing the name of the model.

It doesn't look very nice currently:

- The label is not distinguishable from the name of the model.
- When making the name of the model empty, there is no visual clue that you can
  add a name.

== Step 2 - Adding Style

.Projection with Style
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=ModelBox2]
----

As you can see the `LabelBox` now has the style `demoStyles.keyword` associated with it,
so it will show in a different color.
Also, the `TextBox` has a `placeHolder` property.  This placeholder
will show whenever the contents of the `TextBox` is empty, giving the user a visual clue
that he can should type a name.

The style is defined in a css (or actually scss) as follows:

.CSS for Styled Projection
[source, language=css]
----
include::{src-dir}/demo/src/styles/style.scss[tag=StyleKeyword]
----
The projection now shown the label according to this style.
In principle all CSS style can be used here.

== Step 3 - Showing Contained Elements

We will add the entities owned by the `DemoModel` to the projection.

.Projection of Child Elements
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=ModelBox3]
----
The entities will be below the model name and for this we use a `VerticalListBox`.
First we show the model keyword plus its name,
the we show the keyword _Entities_,
followed by another `VerticalListBox` of all entities.
The projection of an entity is defined in a separate function:

.Projection of Entity
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=EntityBox]
----
This function is very similar to the projection of the model box,
showing the keyword _Entity_ followed by its name and below all attributes of the
entity in a `VerticalListBox`.

Once again, the projection of an attribute is defined in its own function.

.Projection of Attribute
[source]
----
include::{src-dir}/demo/src/editor/TutorialProjection.ts[tag=AttributeBox]
----

== Step 4 - Allow Creation of new Elements in the Editor

The projection sofar is exactly that: a projection.
There are no actions defined yet, which we need to make a functioning editor.

This step is explained in the xref:tutorials/Actions-Tutorial.adoc[Actions] tutorial.
