// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { UndoModelDefaultWorker } from "../utils/gen/index.js";
import { type UndoModelCheckerInterface } from "./gen/UndoModelValidator.js";

export class CustomUndoModelValidator extends UndoModelDefaultWorker implements UndoModelCheckerInterface {
    errorList: FreError[] = [];
}
