export const projectitStyles: {
    variable: string;
    member: string;
    keyword: string;
    numeric: string;
    stringLiteral: string;
    function: string;
    optional: string;
    ifthenelse: string;
    requiredPlaceholder: string;
    grid: string;
    gridcell: string;
    gridcellOr: string;
    gridcellLast: string;
    gridcellFirst: string;
    binary: string;
    mygrid: string;
    mycell: string;
    tree: string;
    indent: string;
    indent2: string;
} = require("./style.scss");
