= ProjectIt
Projectional Editor for the Web.

ProjectIt has been presented at the LangDev workshop in Amsterdam on March 21-22.

**Note**. This project is Work in Progress, no distribution has been made yet. No version numer is attached yet, the first 0.? release will be later this year.

== What is ProjectIt

ProjectIt is a TypeScript/JavaScript framework to create and implement projectional editors for Domain-Specific Languages (DSLs) with.

It is mostly unopinionated with regards to the models that can be projected, as long as you can make it observed using [MobX](https://mobx.js.org/).
The framework provides an internal projection DSL to specify layouts and typical editor behaviour.
It's the job of the developer of the projectional editor to map models to that projection DSL.
The framework provides standard functionality mostly for navigating in the editor, but also for deleting model elements.

ProjectIt provides full support for editing expressions with associativity and precedences.

For creating elements  the DSL implementor needs to 
provide callbacks for manipulating the state of the model based on actions in the editor.

Note: no model (persistence) infrastructure is provided.

== Installation

The main prerequisites are: https://nodejs.org/[Node.js] and https://yarnpkg.com/[yarn].
We are typically using the latest versions of both, although older versions likely work just as well.
You could also try and use NPM instead of yarn.

To install all dependencies:

    yarn install

To build and run the demo locally:

    yarn start

This will open a browser with the demo app on `http://localhost:3000/`.
The demo app is work in progress.

== Source organisation

* `.idea`: workspace files for the JetBrains' WebStorm that we use.
* `.vscode`: workspace files for the Visual Studio Code IDEs that we use (to be done).
* `dist`: target directory for WebPack.
* `docs`: The documentation, generated by antora from `packages/docs`.
* `packages/core`: framework source code.
* `packages/docs`: documentation
* `packages/demo`: source code using the framework to implement a projectional editor for the demo language.
    The main entry point is `packages/demo/src/run.ts`.
* `packages/meta`: source code using the framework to implement a projectional editor for an experimental meta language..
* `packages/model`: source codefor decorators that can be used to easily implement a language that can be directly used by ProjectIt.
* `/*`: the usual suspects.

