import * as fs from "fs";
import { Checker } from "./Checker";
import { Parser, PEG } from "pegjs";
import { MetaLogger } from "../utils/MetaLogger";
// import SyntaxError = PEG.SyntaxError;

const LOGGER = new MetaLogger("PiParser").mute();

// the following two types are used to store the location information from the parser
export type ParseLocation = {
    filename: string;
    start: Location;
    end: Location;
};

export type Location = {
    offset: number;
    line: number;
    column: number;
};

/**
 * Generic Parser, subclasses need to initialize the parser, checker and msg fields.
 */
export class PiParser<DEFINITION> {
    // No known type, as this is a Javascript parser object generated by pegjs.
    parser: Parser;
    checker: Checker<DEFINITION>;
    // msg: string;

    parse(definitionFile: string): DEFINITION {
        // Check language file
        if (!fs.existsSync(definitionFile)) {
            LOGGER.error(this, "definition file '" + definitionFile + "' does not exist, exiting.");
            throw new Error("file not found.");
        }
        const langSpec: string = fs.readFileSync(definitionFile, { encoding: "utf8" });
        // Parse Language file
        let model: DEFINITION = null;
        try {
            this.setCurrentFileName(definitionFile); // sets the filename in the creator functions to the right value
            model = this.parser.parse(langSpec);
        } catch (e) {
            // syntax error
            const errorstr = `${e} 
                ${e.location && e.location.start ?
                    `[file: ${definitionFile}, line ${e.location.start.line}, column ${e.location.start.column}]`
                :
                    ``}`;
            LOGGER.error(this, errorstr);
            throw new Error("syntax error.");
        }
        if (model !== null) {
            this.checker.check(model);
            if (this.checker.hasErrors()) {
                this.checker.errors.forEach(error => LOGGER.error(this, `${definitionFile}: ${error}`));
                // TODO maybe we should add the number of errors to this Error
                throw new Error("checking errors."); // error message
            }
            return model;
        } else {
            throw new Error("parser does not return a language definition.");
        }
    }

    parseMulti(filePaths: string[]): DEFINITION {
        let model: DEFINITION;
        let submodels: DEFINITION[] = [];
        // read the files and parse them separately
        for (const file of filePaths) {
            if (!fs.existsSync(file)) {
                LOGGER.error(this, "definition file '" + file + "' does not exist, exiting.");
                throw new Error("definition file '" + file + "' does not exist, exiting.");
            } else {
                let langSpec: string = "";
                langSpec += fs.readFileSync(file, { encoding: "utf8" }) + "\n";
                try {
                    this.setCurrentFileName(file); // sets the filename in the creator functions to the right value
                    submodels.push(this.parser.parse(langSpec));
                } catch (e) {
                    // throw syntax error, but adjust the location first
                    const errorstr = `${e} ${e.location && e.location.start ?
                        `[file: ${file}, line ${e.location.start.line}, column ${e.location.start.column}]`
                        :
                        ``}`;
                    LOGGER.error(this, errorstr);
                    throw new Error("syntax error.");
                }
            }
        }

        // combine the submodels into one
        model = this.merge(submodels);

        // run the checker
        if (model !== null) {
            this.checker.check(model);
            if (this.checker.hasErrors()) {
                this.checker.errors.forEach(error => LOGGER.error(this, `${error}`));
                // TODO maybe we should add the number of errors to this Error
                throw new Error("checking errors."); // error message
            }
            return model;
        } else {
            throw new Error("parser does not return a language definition.");
        }
    }

    protected merge(submodels: DEFINITION[]): DEFINITION {
        if (submodels.length > 0) {
            throw Error("PiParser.merge should be implemented by its subclasses.");
        }
        return null;
    }

    protected setCurrentFileName(file: string) {
        throw Error("PiParser.setCurrentFileName should be implemented by its subclasses.");
    }
}
