// Generated by the ProjectIt Language Generator.
import { PiError, PiErrorSeverity } from "@projectit/core";
import { VehiclesDefaultWorker } from "../utils/gen/VehiclesDefaultWorker";
import { VehiclesCheckerInterface } from "./gen/VehiclesValidator";

export class CustomVehiclesValidator extends VehiclesDefaultWorker implements VehiclesCheckerInterface {
    errorList: PiError[] = [];
}
