"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MainStudyConfigurationModelInterpreter = void 0;
// Generated by the Freon Language Generator.
// Generated my Freon, will be overwritten with every generation.
var core_1 = require("@freon4dsl/core");
var StudyConfigurationModelInterpreterInit_1 = require("./gen/StudyConfigurationModelInterpreterInit");
var getPropertyFunction = function (node) {
    var index = node.freOwnerDescriptor().propertyIndex;
    return node.freOwnerDescriptor().propertyName + (index !== undefined ? "[" + index + "]" : "");
};
/**
 * Function that returns the concept name for `node`.
 * Used by the interpreter to find which evaluator should be use for each node.
 */
var getConceptFunction = function (node) {
    if (node === undefined) {
        return "";
    }
    return node.freLanguageConcept();
};
/**
 * The facade around the actual interpreter to avoid improper usage.
 * Sets the functions used to access the expression tree.
 * Ensures all internal interpreter state is cleaned when creating a new instance.
 */
var MainStudyConfigurationModelInterpreter = /** @class */ (function () {
    function MainStudyConfigurationModelInterpreter() {
        if (MainStudyConfigurationModelInterpreter.main === null) {
            MainStudyConfigurationModelInterpreter.main = core_1.MainInterpreter.instance(StudyConfigurationModelInterpreterInit_1.StudyConfigurationModelInterpreterInit, getConceptFunction, getPropertyFunction);
        }
    }
    MainStudyConfigurationModelInterpreter.prototype.setTracing = function (value) {
        MainStudyConfigurationModelInterpreter.main.setTracing(value);
    };
    MainStudyConfigurationModelInterpreter.prototype.getTrace = function () {
        return MainStudyConfigurationModelInterpreter.main.getTrace();
    };
    MainStudyConfigurationModelInterpreter.prototype.evaluate = function (node) {
        MainStudyConfigurationModelInterpreter.main.reset();
        try {
            return MainStudyConfigurationModelInterpreter.main.evaluate(node, core_1.InterpreterContext.EMPTY_CONTEXT);
        }
        catch (e) {
            return new core_1.RtError(e.message);
        }
    };
    MainStudyConfigurationModelInterpreter.main = null;
    return MainStudyConfigurationModelInterpreter;
}());
exports.MainStudyConfigurationModelInterpreter = MainStudyConfigurationModelInterpreter;
