:imagesdir: ../../images
:page-nav_order: 20
:page-parent: Under the Hood
:src-dir: ../../../../core/src
:source-language: javascript
:listing-caption: Code Sample
= Support For Expressions

Editing expressions in a projectional editor is a well-known challenge. The representation of an expression
in the AST is highly structured. Yet, because its appearance to the user looks textual, users expect that
the editing behavior resembles classical text editing as much as possible.

In https://www.voelter.de/data/pub/fse2016-projEditing.pdf[Efficiency of Projectional Editing:
A Controlled Experiment] the authors express the problem as follows.

[quote, Markus Voelter a.o., Efficiency of Projectional Editing]
____
*Improving Expression Editing.*
Editing expressions with their fine-grained tree structure is one of the major challenges in a
projectional editor. The inability to insert and remove parentheses in arbitrary places (and
then refactor the treestructure according to the precedence expressed by the parentheses) is an
example.
____

For this reason, ProjectIt has in-build support for expressions. There is extra functionality to
be able to add an expression before or after an existing expression. Secondly, the AST of any binary
expression is automatically balanced.

//TODO further explain what specific support for expressions is implemented



== Balancing the AST

// TODO take some figures from Powerpoints in K:\projectit\underlying-information\projectional-editing-of-expressions
