// Generated by the ProjectIt Language Generator.
import * as uuid from "uuid";
import { PiElement, PiNamedElement, PiExpression, PiBinaryExpression } from "@projectit/core";
import { model } from "@projectit/core";
import { TaxRulesConceptType } from "./TaxRules";
import { IncomeType } from "./IncomeType";
import { TaxPayerType } from "./TaxPayerType";
import { PlaceholderExpression } from "./PlaceholderExpression";
import { Expression } from "./Expression";
import { ComparisonExpression } from "./ComparisonExpression";

@model
export class LessThenExpression extends ComparisonExpression implements PiBinaryExpression {
    readonly $typename: TaxRulesConceptType = "LessThenExpression";

    constructor(id?: string) {
        super(id);

        this.left = new PlaceholderExpression();
        this.right = new PlaceholderExpression();
    }

    piLanguageConcept(): TaxRulesConceptType {
        return this.$typename;
    }

    piIsExpression(): boolean {
        return true;
    }

    piIsBinaryExpression(): boolean {
        return true;
    }

    piIsExpressionPlaceHolder(): boolean {
        return false;
    }

    public piSymbol(): string {
        return "<";
    }

    piPriority(): number {
        return 10;
    }

    public piLeft(): Expression {
        return this.left;
    }

    public piRight(): Expression {
        return this.right;
    }

    public piSetLeft(value: Expression): void {
        this.left = value;
    }

    public piSetRight(value: Expression): void {
        this.right = value;
    }
}
