:imagesdir: ../../images
:page-nav_order: 20
:page-parent: Deeper in the Source Code
:page-grandparent: Deeper in the Source Code
:page-title: The ProjectIt Framework
:page-has_children: true
:page-has_toc: false
:src-dir: ../../../../../core/src
:page-source-language: javascript
:listing-caption: Code Sample
= The ProjectIt Framework

The ProjectIt Editor Framework is written in TypeScript and based on the React Framework. This page provides
an overview of the Framework. If you want to get deeper into this, see the tutorial
xref:../framework-tutorial.adoc[How to Use the ProjectIt Framework].

== Projection Layout Based on Boxes
The layout of every visible element in the editor is based on _boxes_. A box is a rectangular area
in the editor. A box can contain any number of child boxes. Every AST node is projected in a box.

A small example to start with:
====
[#img-package-json]
.Mapping a StringLiteral
image::{imagesdir}/mapping-example-stringliteral.svg[mapping-example-stringliteral]
====

The figure shows the projection of the concept `StringLiteral`. This is mapped to a horizontal list
of a quote ("), an editable text with the value of the StringLiteral, and a closing quote ("). Note
that the quotes are not part of the AST. They are part of the concrete syntax used in this projection
of the AST.

In TypeScript this projection might look something like:
[source]
----
new HorizontalListBox( [
        new LabelBox("\""),
        new TextBox(stringLiteral.value),
        new LabelBox("\"")
    ]);
----
There are a large number of different types of boxes. See xref:different-boxes.adoc[Boxes] for an overview.

Every projection must implement the xref:../generated-code/interfaces.adoc[_PiProjection_] interface.

== Coupling Behavior to Boxes
User actions on boxes need to be translated into interactions with the projected AST. To know which part of the
projection represents the AST node, we give each `Box` in the projection a _role_, which is unique
within its parent box. This way we can identify every box by its model element plus its role.

In the following figure the roles are shown above the boxes in green.
====
[#img-string-literal]
.Mapping a StringLiteral with Roles
image::{imagesdir}/mapping-example-stringliteral-with-roles.svg[]
====
We can now show the full typescript code for this projection. Given that `literal` is the `StringLiteral` object:

[source]
----
include::{src-dir}/test/testeditor/CoreTestProjection.ts[tag=StringLiteral]
----

<1> The overall horizontal list box to group everything
<2> The first label box for the start quote
<3> The text box for the value of the string literal
<4> The second label box for the end quote

The behavior coupled to a _Box_ is defined by an `action`. To identify which action should be executed,
each behavior is specified by:

* one or more _box roles_, specifying that the behavior is only active
in boxes with that specific role,
* a _trigger_, describing the key(s) that will trigger the behavior, and
* an _action_,  which is a typescript/javascript function the will be executed when the
behavior is being triggered.

Actions are further described in xref:defining_actions.adoc[Actions].


