:imagesdir: ../assets/images/
:src-dir: ../../../../../core/src/test
:projectitdir: ../../../../../core
:source-language: javascript
:listing-caption: Code Sample

= ProjectIt: A Projectional Editor for the Web

Release candidate (version 0.0.5)

== Introduction into ProjectIT
ProjectIt is a Language Workbench (in the making). It is a tool for creating mini-languages,
which are also known as Domain Specific Languages. ProjectIt is able to generate an integrated
set of editor, scoper, typer, and validator for your mini-language from a small set of definitions.

The core of ProjectIt is a TypeScript/JavaScript framework for building web-based, projectional
editors. Editing expressions in a projectional editor is a well-known challenge. What makes the
ProjectIt framework unique is the fact that it has built-in support for expressions, so you can
easily make a projectional editor that allows for a natural manner of editing.

On top of the core framework there are currently five generators, each of which generates part
of the work environment for your mini-language: the language structure, the editor, the scoper,
the typer, and the validator.

Currently, ProjectIt does not support the creation of debuggers, interpreters, generators, and
such. Indeed, we have a (large) wish list of extra features that we would like to implement in
the future. Given time, we hope to realize many of these extra items. If you want to know why
we have chosen this development route, read our statement on the philosophy behind the tool.

We assume that people that want to use ProjectIt know all about making mini-languages. For instance,
the terms metamodel, abstract syntax tree, etc, should be familiar. When we address the ProjectIt
user we call him or her a *language engineer*. The people that will be using the generated editor
and its environment are simply called *users*.

So welcome, language engineer, to the world of ProjectIt. In this website you can find information
on the following subjects.

* You could start with finding out what xref:projectional-editing.adoc[projectional editing] is.
* See how you can xref:installing.adoc[install and use] ProjectIt.
* Find out how to define a language and its editor, etc in the xref:tutorials.adoc[tutorials].
* Dive deeper into the xref:generated-code.adoc[structure of the generated code].
* Get to know more about the xref:sourcecode.adoc[meta-code] of ProjectIt.

[.text-center]
This project is supported by https://openmodeling.nl/[openmodeling].
