# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '**' ]
#  pull_request:
#    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    - run: npm install --global yarn@1.22.19
    - run: yarn cache clean --all
    - run: yarn install
    - run: yarn build
    - run: yarn test

#    - name: Send mail
#      if: always()
#      uses: dawidd6/action-send-mail@v2
#      with:
        # mail server settings
#        server_address: smtp.gmail.com
#        server_port: 465
        # user credentials
#        username: ${{ secrets.EMAIL_USERNAME }}
#        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
#        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
#        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
#        to: jos.warmer@openmodeling.nl
        # from email name
#        from: Github Actions
