// Generated by the Freon Language Generator.
// Generated by the Freon Language Generator.
import type {FreNode, FreType, FreTyper} from "@freon4dsl/core";

/**
 * Class 'CustomSvelteTestTyperPart' is meant to be a convenient place to add any
 * custom code for type checking.
 */
export class CustomSvelteTestTyperPart implements FreTyper {
    mainTyper!: FreTyper;

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    isType(node: FreNode): boolean | undefined {
        return undefined;
    }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    inferType(_node: FreNode): FreType | undefined {
        return undefined;
    }

    equals(type1: FreType, type2: FreType): boolean | undefined {
        return undefined;
    }

    conforms(type1: FreType, type2: FreType): boolean | undefined {
        return undefined;
    }

    conformsList(typelist1: FreType[], typelist2: FreType[]): boolean | undefined {
        return undefined;
    }

    commonSuper(typelist: FreType[]): FreType | undefined {
        return undefined;
    }

    public getSuperTypes(type: FreType): FreType[] | undefined {
        return undefined;
    }
}
