// Generated by the ProjectIt Language Generator.
import { PiError, PiErrorSeverity } from "@projectit/core";
import { ProjectXDefaultWorker } from "../utils/gen/ProjectXDefaultWorker";
import { ProjectXCheckerInterface } from "./gen/ProjectXValidator";
import { ExpWithType } from "../language/gen";
import { ProjectXEnvironment } from "../environment/gen/ProjectXEnvironment";

export class CustomProjectXValidator extends ProjectXDefaultWorker implements ProjectXCheckerInterface {
    errorList: PiError[] = [];

    public execBeforeExpWithType(modelelement: ExpWithType): boolean {
        let hasFatalError: boolean = false;
        const typer = ProjectXEnvironment.getInstance().typer;
        const writer = ProjectXEnvironment.getInstance().writer;
        // typecheck equalsType (self.expr, self.type)
        if (!typer.equalsType(modelelement.expr, modelelement.$type)) {
            this.errorList.push(
                new PiError(
                    "Type '" +
                    writer.writeToString(typer.inferType(modelelement.expr)) +
                    "' of [" +
                    writer.writeNameOnly(modelelement.expr) +
                    "] is not equal to " +
                    writer.writeToString(modelelement.$type),
                    modelelement.expr,
                    writer.writeNameOnly(modelelement.expr),
                    PiErrorSeverity.Error
                )
            );
            hasFatalError = true;
        }
        return hasFatalError;
    }
}
